<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class VeiculosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $veiculos = [
            // Toyota
            [
                'marca' => 'Toyota',
                'modelo' => 'Corolla XEi',
                'ano_fabricacao' => 2022,
                'ano_modelo' => 2023,
                'placa' => 'ABC1234',
                'cor' => 'Prata',
                'tipo' => 'Passeio',
                'chassi' => '9BR53ZEC1J8' . rand(100000, 999999),
                'renavam' => rand(10000000000, 99999999999),
                'quilometragem' => rand(5000, 25000),
                'combustivel' => 'Flex',
                'cambio' => 'Automático',
                'portas' => 4,
                'motor' => '2.0 16V',
                'preco_compra' => 85000.00,
                'preco_venda' => 98000.00,
                'status' => 'Disponível',
                'categoria' => 'Seminovo',
                'descricao' => 'Corolla XEi em excelente estado, único dono, revisões em concessionária.',
                'data_aquisicao' => Carbon::now()->subDays(rand(30, 180)),
            ],
            [
                'marca' => 'Toyota',
                'modelo' => 'Hilux SW4 SRX',
                'ano_fabricacao' => 2021,
                'ano_modelo' => 2021,
                'placa' => 'DEF5678',
                'cor' => 'Branco',
                'tipo' => 'SUV',
                'chassi' => '9BR53ZEC2K9' . rand(100000, 999999),
                'renavam' => rand(10000000000, 99999999999),
                'quilometragem' => rand(15000, 45000),
                'combustivel' => 'Diesel',
                'cambio' => 'Automático',
                'portas' => 4,
                'motor' => '2.8 Turbo',
                'preco_compra' => 210000.00,
                'preco_venda' => 235000.00,
                'status' => 'Disponível',
                'categoria' => 'Seminovo',
                'descricao' => 'SW4 SRX completa, 7 lugares, diesel, único dono.',
                'data_aquisicao' => Carbon::now()->subDays(rand(15, 90)),
            ],

            // Honda
            [
                'marca' => 'Honda',
                'modelo' => 'Civic Sport',
                'ano_fabricacao' => 2023,
                'ano_modelo' => 2024,
                'placa' => 'GHI9012',
                'cor' => 'Preto',
                'tipo' => 'Passeio',
                'chassi' => '19XFC2F59ME' . rand(100000, 999999),
                'renavam' => rand(10000000000, 99999999999),
                'quilometragem' => rand(2000, 15000),
                'combustivel' => 'Flex',
                'cambio' => 'CVT',
                'portas' => 4,
                'motor' => '2.0 VTEC',
                'preco_compra' => 115000.00,
                'preco_venda' => 128000.00,
                'status' => 'Disponível',
                'categoria' => 'Seminovo',
                'descricao' => 'Honda Civic Sport com multimídia, bancos em couro.',
                'data_aquisicao' => Carbon::now()->subDays(rand(10, 60)),
            ],
            [
                'marca' => 'Honda',
                'modelo' => 'HR-V EX',
                'ano_fabricacao' => 2020,
                'ano_modelo' => 2020,
                'placa' => 'JKL3456',
                'cor' => 'Azul',
                'tipo' => 'SUV',
                'chassi' => '19XFC1F30KE' . rand(100000, 999999),
                'renavam' => rand(10000000000, 99999999999),
                'quilometragem' => rand(25000, 55000),
                'combustivel' => 'Flex',
                'cambio' => 'CVT',
                'portas' => 4,
                'motor' => '1.8 16V',
                'preco_compra' => 78000.00,
                'preco_venda' => 89000.00,
                'status' => 'Disponível',
                'categoria' => 'Usado',
                'descricao' => 'HR-V EX completo, teto solar, central multimídia.',
                'data_aquisicao' => Carbon::now()->subDays(rand(45, 120)),
            ],

            // Volkswagen
            [
                'marca' => 'Volkswagen',
                'modelo' => 'Golf TSI',
                'ano_fabricacao' => 2021,
                'ano_modelo' => 2022,
                'placa' => 'MNO7890',
                'cor' => 'Vermelho',
                'tipo' => 'Passeio',
                'chassi' => '9BWZZZ377KP' . rand(100000, 999999),
                'renavam' => rand(10000000000, 99999999999),
                'quilometragem' => rand(18000, 35000),
                'combustivel' => 'Gasolina',
                'cambio' => 'Automático',
                'portas' => 4,
                'motor' => '1.4 TSI',
                'preco_compra' => 95000.00,
                'preco_venda' => 108000.00,
                'status' => 'Disponível',
                'categoria' => 'Seminovo',
                'descricao' => 'Golf TSI Highline, motor turbo, interior premium.',
                'data_aquisicao' => Carbon::now()->subDays(rand(20, 95)),
            ],
            [
                'marca' => 'Volkswagen',
                'modelo' => 'Tiguan Allspace',
                'ano_fabricacao' => 2022,
                'ano_modelo' => 2023,
                'placa' => 'PQR1234',
                'cor' => 'Cinza',
                'tipo' => 'SUV',
                'chassi' => '9BWZZZ5N7KP' . rand(100000, 999999),
                'renavam' => rand(10000000000, 99999999999),
                'quilometragem' => rand(8000, 22000),
                'combustivel' => 'Gasolina',
                'cambio' => 'Automático',
                'portas' => 4,
                'motor' => '1.4 TSI',
                'preco_compra' => 155000.00,
                'preco_venda' => 175000.00,
                'status' => 'Disponível',
                'categoria' => 'Seminovo',
                'descricao' => 'Tiguan Allspace 7 lugares, teto panorâmico, tecnologia.',
                'data_aquisicao' => Carbon::now()->subDays(rand(25, 80)),
            ],

            // Ford
            [
                'marca' => 'Ford',
                'modelo' => 'Ranger Limited',
                'ano_fabricacao' => 2023,
                'ano_modelo' => 2023,
                'placa' => 'STU5678',
                'cor' => 'Branco',
                'tipo' => 'Picape',
                'chassi' => '8AFDT13X2K4' . rand(100000, 999999),
                'renavam' => rand(10000000000, 99999999999),
                'quilometragem' => rand(3000, 12000),
                'combustivel' => 'Diesel',
                'cambio' => 'Automático',
                'portas' => 4,
                'motor' => '2.2 Turbo',
                'preco_compra' => 185000.00,
                'preco_venda' => 205000.00,
                'status' => 'Disponível',
                'categoria' => 'Seminovo',
                'descricao' => 'Ranger Limited 4x4, diesel, automática, completa.',
                'data_aquisicao' => Carbon::now()->subDays(rand(12, 50)),
            ],
            [
                'marca' => 'Ford',
                'modelo' => 'EcoSport Titanium',
                'ano_fabricacao' => 2019,
                'ano_modelo' => 2020,
                'placa' => 'VWX9012',
                'cor' => 'Verde',
                'tipo' => 'SUV',
                'chassi' => '8AFDT13X1J4' . rand(100000, 999999),
                'renavam' => rand(10000000000, 99999999999),
                'quilometragem' => rand(35000, 65000),
                'combustivel' => 'Flex',
                'cambio' => 'Automático',
                'portas' => 4,
                'motor' => '2.0 16V',
                'preco_compra' => 68000.00,
                'preco_venda' => 78000.00,
                'status' => 'Disponível',
                'categoria' => 'Usado',
                'descricao' => 'EcoSport Titanium automático, teto solar, multimídia.',
                'data_aquisicao' => Carbon::now()->subDays(rand(60, 150)),
            ],

            // Chevrolet
            [
                'marca' => 'Chevrolet',
                'modelo' => 'Onix Plus Premier',
                'ano_fabricacao' => 2022,
                'ano_modelo' => 2023,
                'placa' => 'YZA3456',
                'cor' => 'Prata',
                'tipo' => 'Passeio',
                'chassi' => '9BGKS19X0MG' . rand(100000, 999999),
                'renavam' => rand(10000000000, 99999999999),
                'quilometragem' => rand(12000, 28000),
                'combustivel' => 'Flex',
                'cambio' => 'Automático',
                'portas' => 4,
                'motor' => '1.0 Turbo',
                'preco_compra' => 75000.00,
                'preco_venda' => 85000.00,
                'status' => 'Disponível',
                'categoria' => 'Seminovo',
                'descricao' => 'Onix Plus Premier turbo, MyLink, sensores.',
                'data_aquisicao' => Carbon::now()->subDays(rand(18, 75)),
            ],
            [
                'marca' => 'Chevrolet',
                'modelo' => 'S10 LTZ',
                'ano_fabricacao' => 2021,
                'ano_modelo' => 2021,
                'placa' => 'BCD7890',
                'cor' => 'Preto',
                'tipo' => 'Picape',
                'chassi' => '9BGKS48X2MG' . rand(100000, 999999),
                'renavam' => rand(10000000000, 99999999999),
                'quilometragem' => rand(22000, 42000),
                'combustivel' => 'Diesel',
                'cambio' => 'Automático',
                'portas' => 4,
                'motor' => '2.8 Turbo',
                'preco_compra' => 145000.00,
                'preco_venda' => 165000.00,
                'status' => 'Disponível',
                'categoria' => 'Usado',
                'descricao' => 'S10 LTZ 4x4 diesel, automática, central multimídia.',
                'data_aquisicao' => Carbon::now()->subDays(rand(35, 110)),
            ],

            // Hyundai
            [
                'marca' => 'Hyundai',
                'modelo' => 'HB20S Evolution',
                'ano_fabricacao' => 2023,
                'ano_modelo' => 2024,
                'placa' => 'EFG1234',
                'cor' => 'Azul',
                'tipo' => 'Passeio',
                'chassi' => '9BHAG41FXKG' . rand(100000, 999999),
                'renavam' => rand(10000000000, 99999999999),
                'quilometragem' => rand(5000, 18000),
                'combustivel' => 'Flex',
                'cambio' => 'Automático',
                'portas' => 4,
                'motor' => '1.0 Turbo',
                'preco_compra' => 82000.00,
                'preco_venda' => 92000.00,
                'status' => 'Disponível',
                'categoria' => 'Seminovo',
                'descricao' => 'HB20S Evolution com Bluelink, teto solar, premium.',
                'data_aquisicao' => Carbon::now()->subDays(rand(8, 45)),
            ],
            [
                'marca' => 'Hyundai',
                'modelo' => 'Creta Ultimate',
                'ano_fabricacao' => 2022,
                'ano_modelo' => 2022,
                'placa' => 'HIJ5678',
                'cor' => 'Branco',
                'tipo' => 'SUV',
                'chassi' => '9BHAG48FXKG' . rand(100000, 999999),
                'renavam' => rand(10000000000, 99999999999),
                'quilometragem' => rand(15000, 32000),
                'combustivel' => 'Flex',
                'cambio' => 'Automático',
                'portas' => 4,
                'motor' => '2.0 16V',
                'preco_compra' => 105000.00,
                'preco_venda' => 118000.00,
                'status' => 'Disponível',
                'categoria' => 'Seminovo',
                'descricao' => 'Creta Ultimate com teto solar, interior premium.',
                'data_aquisicao' => Carbon::now()->subDays(rand(28, 85)),
            ],

            // Nissan
            [
                'marca' => 'Nissan',
                'modelo' => 'Kicks SV',
                'ano_fabricacao' => 2021,
                'ano_modelo' => 2022,
                'placa' => 'KLM9012',
                'cor' => 'Laranja',
                'tipo' => 'SUV',
                'chassi' => '3N1CN7AP7LL' . rand(100000, 999999),
                'renavam' => rand(10000000000, 99999999999),
                'quilometragem' => rand(20000, 38000),
                'combustivel' => 'Flex',
                'cambio' => 'CVT',
                'portas' => 4,
                'motor' => '1.6 16V',
                'preco_compra' => 85000.00,
                'preco_venda' => 95000.00,
                'status' => 'Disponível',
                'categoria' => 'Usado',
                'descricao' => 'Kicks SV com central multimídia, câmera de ré.',
                'data_aquisicao' => Carbon::now()->subDays(rand(42, 125)),
            ],

            // Jeep
            [
                'marca' => 'Jeep',
                'modelo' => 'Compass Limited',
                'ano_fabricacao' => 2022,
                'ano_modelo' => 2023,
                'placa' => 'NOP3456',
                'cor' => 'Cinza',
                'tipo' => 'SUV',
                'chassi' => '1C4NJCBA3KD' . rand(100000, 999999),
                'renavam' => rand(10000000000, 99999999999),
                'quilometragem' => rand(10000, 25000),
                'combustivel' => 'Flex',
                'cambio' => 'Automático',
                'portas' => 4,
                'motor' => '1.3 Turbo',
                'preco_compra' => 135000.00,
                'preco_venda' => 152000.00,
                'status' => 'Disponível',
                'categoria' => 'Seminovo',
                'descricao' => 'Compass Limited 4x4, teto solar, bancos em couro.',
                'data_aquisicao' => Carbon::now()->subDays(rand(15, 70)),
            ],

            // Fiat
            [
                'marca' => 'Fiat',
                'modelo' => 'Argo HGT',
                'ano_fabricacao' => 2020,
                'ano_modelo' => 2021,
                'placa' => 'QRS7890',
                'cor' => 'Vermelho',
                'tipo' => 'Passeio',
                'chassi' => '9BD358000K4' . rand(100000, 999999),
                'renavam' => rand(10000000000, 99999999999),
                'quilometragem' => rand(28000, 48000),
                'combustivel' => 'Flex',
                'cambio' => 'Manual',
                'portas' => 4,
                'motor' => '1.8 16V',
                'preco_compra' => 58000.00,
                'preco_venda' => 68000.00,
                'status' => 'Disponível',
                'categoria' => 'Usado',
                'descricao' => 'Argo HGT esportivo, rodas de liga, multimídia.',
                'data_aquisicao' => Carbon::now()->subDays(rand(55, 140)),
            ],

            // BMW
            [
                'marca' => 'BMW',
                'modelo' => '320i M Sport',
                'ano_fabricacao' => 2021,
                'ano_modelo' => 2022,
                'placa' => 'TUV1234',
                'cor' => 'Azul',
                'tipo' => 'Passeio',
                'chassi' => '3MW5R1J50M8' . rand(100000, 999999),
                'renavam' => rand(10000000000, 99999999999),
                'quilometragem' => rand(15000, 35000),
                'combustivel' => 'Gasolina',
                'cambio' => 'Automático',
                'portas' => 4,
                'motor' => '2.0 Turbo',
                'preco_compra' => 195000.00,
                'preco_venda' => 225000.00,
                'status' => 'Reservado',
                'categoria' => 'Seminovo',
                'descricao' => 'BMW 320i M Sport com pacote esportivo, interior premium.',
                'data_aquisicao' => Carbon::now()->subDays(rand(22, 65)),
            ]
        ];

        // Inserir todos os veículos
        foreach ($veiculos as $veiculo) {
            DB::table('veiculos')->insert(array_merge($veiculo, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}
