<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Veiculo;
use Illuminate\Support\Facades\DB;

class VeiculosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $veiculos = [
            // BMW
            [
                'marca' => 'BMW',
                'modelo' => 'M4 Competition',
                'ano_fabricacao' => 2024,
                'ano_modelo' => 2024,
                'placa' => 'ABC1234',
                'cor' => 'Azul Marina',
                'tipo' => 'Passeio',
                'chassi' => 'WBA3C1109FP12345',
                'renavam' => '12345678901',
                'quilometragem' => 5000,
                'combustivel' => 'Gasolina',
                'cambio' => 'Automático',
                'portas' => 2,
                'motor' => '3.0 Biturbo',
                'preco_compra' => 650000.00,
                'preco_venda' => 750000.00,
                'status' => 'Disponível',
                'categoria' => 'Seminovo',
                'descricao' => 'BMW M4 Competition com motor 3.0 biturbo de 510cv. Performance excepcional e design icônico.',
                'data_aquisicao' => '2024-01-15',
            ],
            [
                'marca' => 'BMW',
                'modelo' => 'X5 xDrive40i',
                'ano_fabricacao' => 2023,
                'ano_modelo' => 2024,
                'placa' => 'DEF5678',
                'cor' => 'Preto Safira',
                'tipo' => 'SUV',
                'chassi' => 'WBA5C1109FP67890',
                'renavam' => '23456789012',
                'quilometragem' => 12000,
                'combustivel' => 'Gasolina',
                'cambio' => 'Automático',
                'portas' => 4,
                'motor' => '3.0 Turbo',
                'preco_compra' => 480000.00,
                'preco_venda' => 550000.00,
                'status' => 'Disponível',
                'categoria' => 'Seminovo',
                'descricao' => 'SUV premium com 7 lugares, tecnologia de ponta e conforto incomparável.',
                'data_aquisicao' => '2024-02-20',
            ],

            // BYD
            [
                'marca' => 'BYD',
                'modelo' => 'Dolphin',
                'ano_fabricacao' => 2024,
                'ano_modelo' => 2024,
                'placa' => 'GHI9012',
                'cor' => 'Branco',
                'tipo' => 'Passeio',
                'chassi' => 'LGXC16DB0P0123456',
                'renavam' => '34567890123',
                'quilometragem' => 2000,
                'combustivel' => 'Elétrico',
                'cambio' => 'Automático',
                'portas' => 4,
                'motor' => 'Elétrico',
                'preco_compra' => 140000.00,
                'preco_venda' => 165000.00,
                'status' => 'Disponível',
                'categoria' => 'Novo',
                'descricao' => '100% elétrico, autonomia de 340km. Design moderno e tecnologia sustentável.',
                'data_aquisicao' => '2024-03-10',
            ],
            [
                'marca' => 'BYD',
                'modelo' => 'Seal',
                'ano_fabricacao' => 2024,
                'ano_modelo' => 2024,
                'placa' => 'JKL3456',
                'cor' => 'Cinza',
                'tipo' => 'Passeio',
                'chassi' => 'LGXC26DB0P0789012',
                'renavam' => '45678901234',
                'quilometragem' => 1000,
                'combustivel' => 'Elétrico',
                'cambio' => 'Automático',
                'portas' => 4,
                'motor' => 'Elétrico',
                'preco_compra' => 280000.00,
                'preco_venda' => 320000.00,
                'status' => 'Disponível',
                'categoria' => 'Novo',
                'descricao' => 'Sedã elétrico premium com 530km de autonomia. Aceleração de 0 a 100km/h em 3.8s.',
                'data_aquisicao' => '2024-04-05',
            ],

            // TOYOTA
            [
                'marca' => 'Toyota',
                'modelo' => 'Corolla XEi',
                'ano_fabricacao' => 2023,
                'ano_modelo' => 2024,
                'placa' => 'MNO7890',
                'cor' => 'Prata',
                'tipo' => 'Passeio',
                'chassi' => '9BR2K16F0P0456789',
                'renavam' => '56789012345',
                'quilometragem' => 18000,
                'combustivel' => 'Flex',
                'cambio' => 'CVT',
                'portas' => 4,
                'motor' => '2.0 16V',
                'preco_compra' => 115000.00,
                'preco_venda' => 135000.00,
                'status' => 'Disponível',
                'categoria' => 'Seminovo',
                'descricao' => 'O sedã mais confiável do Brasil. Baixo consumo e alta durabilidade.',
                'data_aquisicao' => '2024-01-25',
            ],
            [
                'marca' => 'Toyota',
                'modelo' => 'SW4 Diamond',
                'ano_fabricacao' => 2023,
                'ano_modelo' => 2023,
                'placa' => 'PQR1234',
                'cor' => 'Branco Pérola',
                'tipo' => 'SUV',
                'chassi' => '8AJTK16G0P0123456',
                'renavam' => '67890123456',
                'quilometragem' => 25000,
                'combustivel' => 'Diesel',
                'cambio' => 'Automático',
                'portas' => 4,
                'motor' => '2.8 Turbo Diesel',
                'preco_compra' => 320000.00,
                'preco_venda' => 380000.00,
                'status' => 'Disponível',
                'categoria' => 'Seminovo',
                'descricao' => '7 lugares, tração 4x4. Preparado para qualquer terreno com máximo conforto.',
                'data_aquisicao' => '2024-02-10',
            ],

            // RENAULT
            [
                'marca' => 'Renault',
                'modelo' => 'Kwid Zen',
                'ano_fabricacao' => 2023,
                'ano_modelo' => 2024,
                'placa' => 'STU5678',
                'cor' => 'Vermelho',
                'tipo' => 'Passeio',
                'chassi' => '93Y5SRD10P0345678',
                'renavam' => '78901234567',
                'quilometragem' => 15000,
                'combustivel' => 'Flex',
                'cambio' => 'Manual',
                'portas' => 4,
                'motor' => '1.0 12V',
                'preco_compra' => 48000.00,
                'preco_venda' => 58000.00,
                'status' => 'Disponível',
                'categoria' => 'Seminovo',
                'descricao' => 'Compacto e econômico. Ideal para cidade com baixo custo de manutenção.',
                'data_aquisicao' => '2024-03-01',
            ],
            [
                'marca' => 'Renault',
                'modelo' => 'Duster Iconic',
                'ano_fabricacao' => 2024,
                'ano_modelo' => 2024,
                'placa' => 'VWX9012',
                'cor' => 'Cinza Cassiopeia',
                'tipo' => 'SUV',
                'chassi' => '93Y5HSD10P0567890',
                'renavam' => '89012345678',
                'quilometragem' => 8000,
                'combustivel' => 'Flex',
                'cambio' => 'CVT',
                'portas' => 4,
                'motor' => '1.3 Turbo',
                'preco_compra' => 105000.00,
                'preco_venda' => 125000.00,
                'status' => 'Disponível',
                'categoria' => 'Seminovo',
                'descricao' => 'SUV versátil com tração 4x4. Perfeito para aventuras e uso diário.',
                'data_aquisicao' => '2024-04-15',
            ],

            // PEUGEOT
            [
                'marca' => 'Peugeot',
                'modelo' => '208 Allure',
                'ano_fabricacao' => 2023,
                'ano_modelo' => 2024,
                'placa' => 'YZA3456',
                'cor' => 'Azul Vertigo',
                'tipo' => 'Passeio',
                'chassi' => '8AP5FSR10P0234567',
                'renavam' => '90123456789',
                'quilometragem' => 12000,
                'combustivel' => 'Flex',
                'cambio' => 'Automático',
                'portas' => 4,
                'motor' => '1.6 16V',
                'preco_compra' => 78000.00,
                'preco_venda' => 92000.00,
                'status' => 'Disponível',
                'categoria' => 'Seminovo',
                'descricao' => 'Design francês sofisticado com tecnologia e economia.',
                'data_aquisicao' => '2024-02-28',
            ],
            [
                'marca' => 'Peugeot',
                'modelo' => '3008 Griffe',
                'ano_fabricacao' => 2023,
                'ano_modelo' => 2023,
                'placa' => 'BCD7890',
                'cor' => 'Preto Perla',
                'tipo' => 'SUV',
                'chassi' => '8AP5GTR10P0456789',
                'renavam' => '01234567890',
                'quilometragem' => 20000,
                'combustivel' => 'Flex',
                'cambio' => 'Automático',
                'portas' => 4,
                'motor' => '1.6 Turbo',
                'preco_compra' => 155000.00,
                'preco_venda' => 185000.00,
                'status' => 'Disponível',
                'categoria' => 'Seminovo',
                'descricao' => 'SUV premium com i-Cockpit, bancos massageadores e muita tecnologia.',
                'data_aquisicao' => '2024-01-20',
            ],

            // CHEVROLET
            [
                'marca' => 'Chevrolet',
                'modelo' => 'Onix Plus Premier',
                'ano_fabricacao' => 2024,
                'ano_modelo' => 2024,
                'placa' => 'EFG1234',
                'cor' => 'Branco Summit',
                'tipo' => 'Passeio',
                'chassi' => '9BGKS69X0P0123456',
                'renavam' => '11234567890',
                'quilometragem' => 5000,
                'combustivel' => 'Flex',
                'cambio' => 'Automático',
                'portas' => 4,
                'motor' => '1.0 Turbo',
                'preco_compra' => 85000.00,
                'preco_venda' => 98000.00,
                'status' => 'Disponível',
                'categoria' => 'Novo',
                'descricao' => 'O sedã compacto mais vendido do Brasil. Moderno, econômico e espaçoso.',
                'data_aquisicao' => '2024-05-01',
            ],
            [
                'marca' => 'Chevrolet',
                'modelo' => 'Tracker Premier',
                'ano_fabricacao' => 2023,
                'ano_modelo' => 2024,
                'placa' => 'HIJ5678',
                'cor' => 'Cinza Graphite',
                'tipo' => 'SUV',
                'chassi' => '9BGKS79X0P0789012',
                'renavam' => '21234567891',
                'quilometragem' => 15000,
                'combustivel' => 'Flex',
                'cambio' => 'Automático',
                'portas' => 4,
                'motor' => '1.2 Turbo',
                'preco_compra' => 125000.00,
                'preco_venda' => 145000.00,
                'status' => 'Disponível',
                'categoria' => 'Seminovo',
                'descricao' => 'SUV compacto com design arrojado e muita tecnologia embarcada.',
                'data_aquisicao' => '2024-03-15',
            ],

            // FIAT
            [
                'marca' => 'Fiat',
                'modelo' => 'Argo Trekking',
                'ano_fabricacao' => 2023,
                'ano_modelo' => 2024,
                'placa' => 'KLM9012',
                'cor' => 'Verde Portofino',
                'tipo' => 'Passeio',
                'chassi' => '9BD358100P0234567',
                'renavam' => '31234567892',
                'quilometragem' => 22000,
                'combustivel' => 'Flex',
                'cambio' => 'Manual',
                'portas' => 4,
                'motor' => '1.3 8V',
                'preco_compra' => 62000.00,
                'preco_venda' => 75000.00,
                'status' => 'Disponível',
                'categoria' => 'Usado',
                'descricao' => 'Hatchback aventureiro com visual robusto e ótimo custo-benefício.',
                'data_aquisicao' => '2024-02-05',
            ],
            [
                'marca' => 'Fiat',
                'modelo' => 'Toro Ultra',
                'ano_fabricacao' => 2023,
                'ano_modelo' => 2023,
                'placa' => 'NOP3456',
                'cor' => 'Preto Carbon',
                'tipo' => 'Picape',
                'chassi' => '9BD358200P0567890',
                'renavam' => '41234567893',
                'quilometragem' => 28000,
                'combustivel' => 'Diesel',
                'cambio' => 'Automático',
                'portas' => 4,
                'motor' => '2.0 Turbo Diesel',
                'preco_compra' => 155000.00,
                'preco_venda' => 180000.00,
                'status' => 'Disponível',
                'categoria' => 'Seminovo',
                'descricao' => 'Picape média com tração 4x4, potência e conforto de SUV.',
                'data_aquisicao' => '2024-01-10',
            ],

            // FORD
            [
                'marca' => 'Ford',
                'modelo' => 'Ranger XLT',
                'ano_fabricacao' => 2023,
                'ano_modelo' => 2023,
                'placa' => 'QRS7890',
                'cor' => 'Prata Moonstone',
                'tipo' => 'Picape',
                'chassi' => '8AFBR13E0P0123456',
                'renavam' => '51234567894',
                'quilometragem' => 35000,
                'combustivel' => 'Diesel',
                'cambio' => 'Automático',
                'portas' => 4,
                'motor' => '2.0 Bi-Turbo',
                'preco_compra' => 210000.00,
                'preco_venda' => 245000.00,
                'status' => 'Disponível',
                'categoria' => 'Usado',
                'descricao' => 'Picape robusta e potente. Ideal para trabalho e lazer.',
                'data_aquisicao' => '2023-12-20',
            ],
            [
                'marca' => 'Ford',
                'modelo' => 'Territory Titanium',
                'ano_fabricacao' => 2024,
                'ano_modelo' => 2024,
                'placa' => 'TUV1234',
                'cor' => 'Azul Shark',
                'tipo' => 'SUV',
                'chassi' => '8AFBR23E0P0789012',
                'renavam' => '61234567895',
                'quilometragem' => 3000,
                'combustivel' => 'Gasolina',
                'cambio' => 'Automático',
                'portas' => 4,
                'motor' => '1.5 Turbo',
                'preco_compra' => 165000.00,
                'preco_venda' => 190000.00,
                'status' => 'Disponível',
                'categoria' => 'Novo',
                'descricao' => 'SUV moderno com 7 lugares e tecnologia SYNC 4.',
                'data_aquisicao' => '2024-05-10',
            ],
        ];

        foreach ($veiculos as $veiculo) {
            Veiculo::create($veiculo);
        }
    }
}
